# Generated by Django 2.2.16 on 2022-11-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postsq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('text', models.TextField(help_text='Оставьте комментарий', verbose_name='Текст комментария')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
