# Generated by Django 2.2.16 on 2022-11-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_postsq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postsq',
        ),
    ]
