# Generated by Django 2.2.16 on 2022-11-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20221122_1553'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_followings',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_following'),
        ),
    ]
